name: weather
description: weather app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  provider: ^6.0.5
  shared_preferences: ^2.0.16
  get_it: ^7.2.0
  lottie: ^2.2.0
  draggable_home: ^1.0.4
  internet_connection_checker_plus: ^1.0.1
  dio: ^4.0.6
  quickalert: ^1.0.1
  universal_io: ^2.0.4
  intl: ^0.17.0
  introduction_screen: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/json/weatherNotFound.json
    - assets/json/weather.json
    - assets/images/night.jpg
    - assets/images/morning.jpg
    - assets/json/locationMark.json
    - assets/images/logo.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
flutter_intl:
  enabled: true